version: 2
updates:
  # Rust (Cargo)
  - package-ecosystem: "cargo"
    directory: "/" # где лежит Cargo.toml
    schedule:
      interval: "weekly"
    target-branch: "dev"

  # Node.js (npm/pnpm/yarn)
  - package-ecosystem: "npm"
    directory: "/ui" # где лежит package.json для ui
    schedule:
      interval: "weekly"
    target-branch: "dev"
