import type { Account } from "./types";
import type { Chat, Message, GroupInfo, Member, MediaItem } from "./messengerTypes";

// Authentication Mock Data
export const MOCK_ACCOUNTS: Account[] = [
  {
    username: "alice_smith",
    user_id: 1,
    public_address: "0x1234567890abcdef1234567890abcdef12345678",
    server_address: "https://api.example.com",
  },
  {
    username: "bob_johnson",
    user_id: 2,
    public_address: "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd",
    server_address: "https://api.example.com",
  },
  {
    username: "charlie_brown",
    user_id: 3,
    public_address: "0xfedcba9876543210fedcba9876543210fedcba98",
    server_address: "https://api.example.com",
  },
  {
    username: "diana_prince",
    user_id: 4,
    public_address: "0x9876543210abcdef9876543210abcdef98765432",
    server_address: "https://api.example.com",
    encrypted: true,
  },
];

export const EMPTY_ACCOUNTS: Account[] = [];

// Messenger Mock Data
export const MOCK_CHATS: Chat[] = [
  {
    id: 'chat_1',
    name: 'DM Visuals',
    lastMessage: 'Hey! How are you doing?',
    lastMessageTime: '2 mins',
    unreadCount: 2,
    isGroup: true,
  },
  {
    id: 'chat_2',
    name: 'Bob Johnson',
    lastMessage: 'Sounds good, let me know',
    lastMessageTime: '15 mins',
    unreadCount: 0,
    isGroup: false,
  },
  {
    id: 'chat_3',
    name: 'Project Team',
    lastMessage: 'Diana: The deployment is live now',
    lastMessageTime: '1 hour',
    unreadCount: 3,
    isGroup: true,
  },
  {
    id: 'chat_4',
    name: 'Charlie Brown',
    lastMessage: 'See you tomorrow!',
    lastMessageTime: '3 hours',
    unreadCount: 0,
    isGroup: false,
  },
  {
    id: 'chat_5',
    name: 'Design Discussion',
    lastMessage: 'Eva: I uploaded the new mockups',
    lastMessageTime: 'Yesterday',
    unreadCount: 1,
    isGroup: true,
  },
];

export const MOCK_MESSAGES_BY_CHAT: Record<string, Message[]> = {
  chat_1: [
    {
      id: 'msg_1',
      senderId: 'user_alice',
      senderName: 'Alice Smith',
      content: 'Hey! How are you doing?',
      timestamp: '2:30 PM',
      isOwn: false,
      status: 'read',
    },
    {
      id: 'msg_2',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_3',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_4',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_5',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_6',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_7',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_8',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_9',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_17',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_10',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_11',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_12',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_13',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_14',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Hi Alice! Doing great, thanks for asking!',
      timestamp: '2:31 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_15',
      senderId: 'user_alice',
      senderName: 'Alice Smith',
      content: 'Nice! Are you free this weekend?',
      timestamp: '2:32 PM',
      isOwn: false,
      status: 'read',
    },
    {
      id: 'msg_16',
      senderId: 'current_user',
      senderName: 'You',
      content: 'I think so, what did you have in mind?',
      timestamp: '2:33 PM',
      isOwn: true,
      status: 'read',
    },
  ],
  chat_2: [
    {
      id: 'msg_5',
      senderId: 'user_bob',
      senderName: 'Bob Johnson',
      content: 'Did you review the document?',
      timestamp: '1:15 PM',
      isOwn: false,
      status: 'read',
    },
    {
      id: 'msg_6',
      senderId: 'current_user',
      senderName: 'You',
      content: 'Yes, looks good overall',
      timestamp: '1:45 PM',
      isOwn: true,
      status: 'read',
    },
    {
      id: 'msg_7',
      senderId: 'user_bob',
      senderName: 'Bob Johnson',
      content: 'Sounds good, let me know',
      timestamp: '2:10 PM',
      isOwn: false,
      status: 'read',
    },
  ],
  chat_3: [
    {
      id: 'msg_8',
      senderId: 'user_charlie',
      senderName: 'Charlie Brown',
      content: 'The build is ready for testing',
      timestamp: '11:20 AM',
      isOwn: false,
      status: 'read',
    },
    {
      id: 'msg_9',
      senderId: 'user_diana',
      senderName: 'Diana Prince',
      content: 'Great! QA team is reviewing now',
      timestamp: '11:45 AM',
      isOwn: false,
      status: 'read',
    },
    {
      id: 'msg_10',
      senderId: 'current_user',
      senderName: 'You',
      content: 'I can assist with manual testing if needed',
      timestamp: '12:00 PM',
      isOwn: true,
      status: 'sent',
    },
    {
      id: 'msg_11',
      senderId: 'user_diana',
      senderName: 'Diana Prince',
      content: 'The deployment is live now',
      timestamp: '1:30 PM',
      isOwn: false,
      status: 'read',
    },
  ],
};

// Group Info Mock Data
export const MOCK_GROUP_INFO: Record<string, GroupInfo> = {
  chat_1: {
    chatId: 'chat_1',
    photos: [
      { id: 'photo_1', type: 'photo', url: '/placeholder1.jpg', timestamp: '2 days ago' },
      { id: 'photo_2', type: 'photo', url: '/placeholder2.jpg', timestamp: '3 days ago' },
      { id: 'photo_3', type: 'photo', url: '/placeholder3.jpg', timestamp: '5 days ago' },
      { id: 'photo_4', type: 'photo', url: '/placeholder4.jpg', timestamp: '1 week ago' },
    ],
    audio: [
      { id: 'audio_1', type: 'audio', name: 'Voice Message 1.mp3', size: '1.2 MB', timestamp: 'Yesterday' },
      { id: 'audio_2', type: 'audio', name: 'Recording.mp3', size: '2.5 MB', timestamp: '2 days ago' },
    ],
    videos: [
      { id: 'video_1', type: 'video', name: 'Demo Video.mp4', size: '15 MB', timestamp: '3 days ago' },
      { id: 'video_2', type: 'video', name: 'Tutorial.mp4', size: '22 MB', timestamp: '1 week ago' },
    ],
    documents: [
      { id: 'doc_1', type: 'document', name: 'Project_Proposal.pdf', size: '2.4 MB', timestamp: 'Today' },
      { id: 'doc_2', type: 'document', name: 'Meeting_Notes.docx', size: '156 KB', timestamp: 'Yesterday' },
      { id: 'doc_3', type: 'document', name: 'Budget_2024.xlsx', size: '890 KB', timestamp: '2 days ago' },
    ],
    members: [
      { id: 'member_1', name: 'Ryan Brooks', email: 'ryan28@gmail.com' },
      { id: 'member_2', name: 'Sophia Lin', email: 'sophia99@gmail.com' },
      { id: 'member_3', name: 'Ella Kim', email: 'toella@gmail.com' },
    ],
  },
  chat_3: {
    chatId: 'chat_3',
    photos: [],
    audio: [],
    videos: [],
    documents: [],
    members: [
      { id: 'member_4', name: 'Charlie Brown', email: 'charlie@example.com' },
      { id: 'member_5', name: 'Diana Prince', email: 'diana@example.com' },
    ],
  },
};
