name: "publish"

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Ship repo
        uses: actions/checkout@v4

      - name: Checkout Sea repo
        uses: actions/checkout@v4
        with:
          repository: DeepSeaNet/Sea
          path: Sea
          token: ${{ secrets.DEAP_SEA_NET_PAT }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Install frontend dependencies
        run: pnpm install

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './ -> target'
          
      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '21.x'

      - name: Verify protoc
        run: protoc --version
      
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.bat
      
      - name: Install OpenSSL via vcpkg
        run: ./vcpkg/vcpkg install openssl:x64-windows
      
      - name: Set environment variables for OpenSSL
        run: |
          echo "OPENSSL_DIR=$(pwd)/vcpkg/installed/x64-windows" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$(pwd)/vcpkg/installed/x64-windows/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$(pwd)/vcpkg/installed/x64-windows/lib" >> $GITHUB_ENV

      - name: Verify OpenSSL installation and env
        shell: pwsh
        run: |
          Write-Host "=== Checking OpenSSL version ==="
          try {
              $version = & openssl version
              Write-Host "OpenSSL version: $version"
          } catch {
              Write-Error "OpenSSL is not installed or not found in PATH"
              exit 1
          }
      
          Write-Host "=== Checking OpenSSL environment variables ==="
          if (-not $env:OPENSSL_DIR) {
              Write-Error "OPENSSL_DIR is not set!"
              exit 1
          } else {
              Write-Host "OPENSSL_DIR = $env:OPENSSL_DIR"
          }
      
          if (-not $env:OPENSSL_INCLUDE_DIR) {
              Write-Error "OPENSSL_INCLUDE_DIR is not set!"
              exit 1
          } else {
              Write-Host "OPENSSL_INCLUDE_DIR = $env:OPENSSL_INCLUDE_DIR"
          }
      
          if (-not $env:OPENSSL_LIB_DIR) {
              Write-Error "OPENSSL_LIB_DIR is not set!"
              exit 1
          } else {
              Write-Host "OPENSSL_LIB_DIR = $env:OPENSSL_LIB_DIR"
          }

          
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEA_PATH: Sea
        with:
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
